### ISSUE TITLE
Python buildpack might not work well when requirements.txt is changed

### ISSUE THREAD

**Issue by toolness** [18F/cf-dockerized-buildpack#4]
So the Dockerized Python buildpack helped me out today!  I was having trouble because `cf push` was saying the buildpack failed but `cf logs` wasn't giving me useful info, so I used the Dockerized buildpack to simulate the push on my local machine, and it gave me the debugging info I needed!

Woot!

Except to fix the issue, I had to add a new dependency to my `requirements.txt`.  When I re-ran `docker-compose build`, it *seemed* to say it had installed my new dependency, but when I ran `docker-compose up` again, there was an `ImportError` when my code tried importing it. Weird! A `docker-compose rm` followed by another `docker-compose build` seemed to fix things, though.

**Comment by LinuxBozo** [comment]
I've seen similar with the nodejs buildpack as well recently. I think something changed in the lifecycle that causes this now. Will definitely have to investigate.

**Comment by LinuxBozo** [comment]
So, I've tracked this down to the `.cloudfoundry` and `.profile.d` volumes. New bits that get installed during a re-build don't get copied to the existing volumes when they are mounted, only when they are mounted the first time. So this makes sense that the `rm` would make this work again, since it would remove those volumes. Will have to update documentation with this step.
